# Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
import collections
import os
import json
import pickle

from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_predict

import warnings
warnings.filterwarnings('ignore')

# Load the Train Test Split

In [14]:
X_train = np.load(os.path.join("..", "IPD", "x_train.npy"))
X_test = np.load(os.path.join("..", "IPD", "x_test.npy"))
Y_train = np.load(os.path.join("..", "IPD", "y_train.npy"))
Y_test = np.load(os.path.join("..", "IPD", "y_test.npy"))
print("Training samples : {} \nTesting Samples : {}".format(X_train.shape, X_test.shape))
print("Training Labels : {} \nTesting Labels : {}".format(Y_train.shape, Y_test.shape))

Training samples : (332, 250, 12) 
Testing Samples : (83, 250, 12)
Training Labels : (332,) 
Testing Labels : (83,)


In [15]:
_ , num_timeframes, num_features = X_train.shape

# Reshape data for the model
-----------------
Samples are a 2D matrix which need to be reshaped to 1D to feed into the model

In [16]:
X_train = X_train.reshape((-1,num_timeframes*num_features))
X_test = X_test.reshape((-1,num_timeframes*num_features))
print("Training samples : {} \nTesting Samples : {}".format(X_train.shape, X_test.shape))
print("Training Labels : {} \nTesting Labels : {}".format(Y_train.shape, Y_test.shape))

Training samples : (332, 3000) 
Testing Samples : (83, 3000)
Training Labels : (332,) 
Testing Labels : (83,)


# Grid search over XGBoost model

In [17]:
parameters = {
    'max_depth': [6,7,8,9],
    'n_estimators': [12, 14, 16],
    'learning_rate': [0.15, 0.2, 0.25],
    'gamma':[1.0, 1.5, 2.0]
}
xgb = XGBClassifier(objective='multi:softmax', tree_method='auto', colsample_bytree=0.8, colsample_bylevel=0.8, colsample_bynode=0.8)
grid = GridSearchCV(xgb, parameters, cv=3, scoring='accuracy', verbose=2)
grid.fit(X_train, Y_train)

Fitting 3 folds for each of 108 candidates, totalling 324 fits
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12 .....


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12, total=   1.1s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12 .....


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.0s remaining:    0.0s


[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12, total=   1.1s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=12, total=   1.2s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.3s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.3s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.3s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=16, total=   1.4s
[CV] gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=1.0, learning_rate=0.15, max_depth=6, n_estimators=16, total=   1.5s
[CV] ga

[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=12, total=   1.5s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14, total=   1.8s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14, total=   2.0s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=14, total=   2.0s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.2s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.1s
[CV] gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.1s
[CV] gamma=1.0

[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.9s
[CV] gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.8s
[CV] gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.8s
[CV] gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16, total=   2.2s
[CV] gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16, total=   2.3s
[CV] gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=6, n_estimators=16, total=   2.0s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=12 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=12, total=   1.6s
[CV] ga

[CV]  gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=14, total=   1.9s
[CV] gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=14 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=14, total=   1.9s
[CV] gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.2s
[CV] gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.3s
[CV] gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.0s
[CV] gamma=1.5, learning_rate=0.2, max_depth=9, n_estimators=12 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=9, n_estimators=12, total=   1.6s
[CV] gamma=1.5, learning_rate=0.2, max_depth=9, n_estimators=12 ......
[CV]  gamma=1.5, learning_rate=0.2, max_depth=9, n_estimators=12, total=   1.6s
[CV] gamma=1.5

[CV]  gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.4s
[CV] gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=14 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=14, total=   1.4s
[CV] gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16, total=   1.8s
[CV] gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16, total=   1.7s
[CV] gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=6, n_estimators=16, total=   1.6s
[CV] gamma=2.0, learning_rate=0.15, max_depth=7, n_estimators=12 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=7, n_estimators=12, total=   1.2s
[CV] gamma=2.0, learning_rate=0.15, max_depth=7, n_estimators=12 .....
[CV]  gamma=2.0, learning_rate=0.15, max_depth=7, n_estimators=12, total=   1.3s
[CV] ga

[CV]  gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=14, total=   1.9s
[CV] gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.2s
[CV] gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.4s
[CV] gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=8, n_estimators=16, total=   2.2s
[CV] gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12, total=   1.6s
[CV] gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12, total=   1.6s
[CV] gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12 ......
[CV]  gamma=2.0, learning_rate=0.2, max_depth=9, n_estimators=12, total=   1.7s
[CV] gamma=2.0

[Parallel(n_jobs=1)]: Done 324 out of 324 | elapsed: 10.3min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=0.8,
                                     colsample_bynode=0.8, colsample_bytree=0.8,
                                     gamma=None, gpu_id=None,
                                     importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimato...
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method='auto',
                                     validate_parameters=Fals

In [18]:
params = grid.best_params_
best_estimator = grid.best_estimator_
print(params)
print(best_estimator)

{'gamma': 1.0, 'learning_rate': 0.2, 'max_depth': 8, 'n_estimators': 16}
XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=0.8,
              colsample_bynode=0.8, colsample_bytree=0.8, gamma=1.0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.2, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=16, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='auto', validate_parameters=False, verbosity=None)


In [19]:
clf = best_estimator
clf.fit(X_train,Y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=0.8,
              colsample_bynode=0.8, colsample_bytree=0.8, gamma=1.0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.2, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=16, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='auto', validate_parameters=False, verbosity=None)

In [20]:
Y_pred = clf.predict(X_test)
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89        13
           1       0.85      0.73      0.79        15
           2       0.88      1.00      0.93        14
           3       1.00      1.00      1.00         9
           4       0.78      0.70      0.74        20
           5       0.62      0.67      0.64        12

    accuracy                           0.82        83
   macro avg       0.83      0.84      0.83        83
weighted avg       0.82      0.82      0.82        83

[[12  1  0  0  0  0]
 [ 1 11  2  0  0  1]
 [ 0  0 14  0  0  0]
 [ 0  0  0  9  0  0]
 [ 1  1  0  0 14  4]
 [ 0  0  0  0  4  8]]


# Train on entire data

In [9]:
X_train = np.load(os.path.join("..", "IPD", "x_train.npy"))
X_test = np.load(os.path.join("..", "IPD", "x_test.npy"))
Y_train = np.load(os.path.join("..", "IPD", "y_train.npy"))
Y_test = np.load(os.path.join("..", "IPD", "y_test.npy"))

X_train = np.concatenate((X_train,X_test), axis=0)
Y_train = np.concatenate((Y_train,Y_test), axis=0)

_ , num_timeframes, num_features = X_train.shape
X_train = X_train.reshape((-1,num_timeframes*num_features))
from scipy.sparse import coo_matrix
X_sparse = coo_matrix(X_train)

from sklearn.utils import shuffle
X_train, X_sparse, Y_train = shuffle(X_train, X_sparse, Y_train)
X_train = X_train.reshape((-1,num_timeframes,num_features))

In [10]:
X_train = X_train.reshape((-1,num_timeframes*num_features))
X_test = X_test.reshape((-1,num_timeframes*num_features))
print("Training samples : {} \nTesting Samples : {}".format(X_train.shape, X_test.shape))
print("Training Labels : {} \nTesting Labels : {}".format(Y_train.shape, Y_test.shape))

Training samples : (415, 3000) 
Testing Samples : (83, 3000)
Training Labels : (415,) 
Testing Labels : (83,)


In [11]:
parameters = {
    'max_depth': [7,8,9],
    'n_estimators': [15, 20, 25],
    'learning_rate': [0.15, 0.2, 0.25],
    'gamma':[0.5, 1.0, 1.5]
}
xgb = XGBClassifier(objective='multi:softmax', tree_method='auto', colsample_bytree=0.8, colsample_bylevel=0.8, colsample_bynode=0.8)
grid = GridSearchCV(xgb, parameters, cv=3, scoring='accuracy', verbose=2)
grid.fit(X_train, Y_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15 .....


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15, total=   1.7s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15 .....


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.6s remaining:    0.0s


[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15, total=   1.6s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=15, total=   1.7s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.2s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.1s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=25 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=25, total=   2.8s
[CV] gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=25 .....
[CV]  gamma=0.5, learning_rate=0.15, max_depth=7, n_estimators=25, total=   2.7s
[CV] ga

[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=15, total=   1.7s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20, total=   2.2s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.4s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.7s
[CV] gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=0.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.7s
[CV] ga

[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=15, total=   1.7s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20, total=   2.5s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25, total=   3.1s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25, total=   2.8s
[CV] gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25 ......
[CV]  gamma=1.0, learning_rate=0.2, max_depth=7, n_estimators=25, total=   2.9s
[CV] gamma=1.0

[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.5s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=20 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.2s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=20 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=20, total=   2.2s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25, total=   2.9s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25, total=   3.0s
[CV] gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=7, n_estimators=25, total=   3.0s
[CV] gamma=1.5, learning_rate=0.15, max_depth=8, n_estimators=15 .....
[CV]  gamma=1.5, learning_rate=0.15, max_depth=8, n_estimators=15, total=   1.9s
[CV] ga

[CV]  gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=20, total=   2.3s
[CV] gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=20 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=20, total=   2.1s
[CV] gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.9s
[CV] gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.7s
[CV] gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=7, n_estimators=25, total=   2.8s
[CV] gamma=1.5, learning_rate=0.25, max_depth=8, n_estimators=15 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=8, n_estimators=15, total=   1.7s
[CV] gamma=1.5, learning_rate=0.25, max_depth=8, n_estimators=15 .....
[CV]  gamma=1.5, learning_rate=0.25, max_depth=8, n_estimators=15, total=   2.0s
[CV] ga

[Parallel(n_jobs=1)]: Done 243 out of 243 | elapsed:  9.8min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=0.8,
                                     colsample_bynode=0.8, colsample_bytree=0.8,
                                     gamma=None, gpu_id=None,
                                     importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimato...
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method='auto',
                                     validate_parameters=Fals

In [12]:
clf = grid.best_estimator_
clf.fit(X_train,Y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=0.8,
              colsample_bynode=0.8, colsample_bytree=0.8, gamma=0.5, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.25, max_delta_step=0, max_depth=9,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=20, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='auto', validate_parameters=False, verbosity=None)

# Saving model

In [13]:
pickle.dump(clf, open(os.path.join("..", "IPD", "XGBoost_model.pkl"), 'wb'))
print("Model Saved")

Model Saved
